<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE TOUCHGRAPH_LB [

<!ELEMENT TOUCHGRAPH_LB (NODESET, EDGESET, PARAMETERS)>
<!ELEMENT NODESET (NODE+)>
<!ELEMENT EDGESET (EDGE*)>
<!ELEMENT PARAMETERS (PARAM*)>

<!ELEMENT NODE (NODE_LOCATION?, NODE_LABEL?, NODE_URL?, NODE_HINT?)>

<!ELEMENT NODE_LABEL EMPTY>
<!ELEMENT NODE_URL EMPTY>
<!ELEMENT NODE_HINT EMPTY>

<!ATTLIST TOUCHGRAPH_LB
  version CDATA #REQUIRED >

<!ATTLIST NODE
  nodeID CDATA #REQUIRED >

<!ATTLIST NODE_LOCATION
  visible CDATA #IMPLIED
  x CDATA #IMPLIED
  y CDATA #IMPLIED >

<!ATTLIST NODE_LABEL
  label CDATA #REQUIRED 
  shape CDATA #IMPLIED
  backColor CDATA #IMPLIED 
  textColor CDATA #IMPLIED
  fontSize CDATA #IMPLIED >

<!ATTLIST NODE_URL 
  url CDATA #REQUIRED 
  urlIsLocal CDATA #IMPLIED 
  urlIsXML CDATA #IMPLIED >

<!ATTLIST NODE_HINT 
  hint CDATA #REQUIRED 
  height CDATA #IMPLIED 
  width CDATA #IMPLIED 
  isHTML CDATA #IMPLIED >  

<!ELEMENT EDGE EMPTY>

<!ATTLIST EDGE
  fromID CDATA #REQUIRED
  toID CDATA #REQUIRED 
  length CDATA #IMPLIED 
  color CDATA #IMPLIED 
  type CDATA #IMPLIED
  visible CDATA #IMPLIED >

<!ELEMENT PARAM EMPTY>

<!ATTLIST PARAM
  name CDATA #REQUIRED
  value CDATA #REQUIRED >
]>
<TOUCHGRAPH_LB version="1.20">
    <NODESET>
        <NODE nodeID="AutoID 1010274102450">
            <NODE_LOCATION x="534" y="87" visible="true"/>
            <NODE_LABEL label="Hints" shape="2" backColor="00A0F0" textColor="FFFFFF" fontSize="18"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
		<NODE_HINT hint="&lt;center&gt;&lt;font size=4&gt;&lt;font color =&quot;#00A0F0&quot;&gt;&lt;b&gt;Hints&lt;/b&gt;&lt;/font&gt; are the coolest new feature&lt;/font&gt;&lt;/center&gt;" width="150" height="-1" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1010274200280">
            <NODE_LOCATION x="633" y="30" visible="true"/>
            <NODE_LABEL label="  New Features:  " shape="3" backColor="FF00FF" textColor="FFFFFF" fontSize="18"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="&lt;center&gt;&lt;font size=4&gt;There are lots of&lt;br&gt;&lt;font color=&quot;#ff00ff&quot;&gt; &lt;b&gt;New Features&lt;b&gt;&lt;/font&gt;&lt;/font&gt;&lt;/center&gt;" width="200" height="-1" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1010274564490">
            <NODE_LOCATION x="633" y="-67" visible="true"/>
            <NODE_LABEL label="Welcome!" shape="2" backColor="F0A000" textColor="FFFFFF" fontSize="16"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="&lt;center&gt;&lt;table cellSpacing=0 cellPadding=6 border=5 bordercolor=&quot;#c0c0ff&quot; bgcolor=&quot;#0000ff&quot;&gt;
&lt;td&gt;&lt;font face=&quot;arial&quot; size=&quot;3&quot; color=&quot;#ffd840&quot;&gt;&lt;span class=&quot;arial36&quot;&gt;&lt;b&gt;TouchGraph LinkBrowser&lt;font color=&quot;#FFFFFF&quot;&gt; V1.20&lt;/font&gt;&lt;/b&gt;&lt;/span&gt;&lt;/font&gt;&lt;/td&gt;
&lt;/table&gt;&lt;/center&gt;
" width="300" height="-1" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1010377764880">
            <NODE_LOCATION x="377" y="310" visible="false"/>
            <NODE_LABEL label="Can have hypertext" shape="2" backColor="F05050" textColor="FFFFFF" fontSize="14"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="&lt;center&gt;&lt;font color=&quot;#F05050&quot; size =&quot;20&quot;&gt;&lt;blink&gt;Hypertext!&lt;/blink&gt;&lt;/font&gt;&lt;/center&gt;" width="200" height="-1" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1010377835240">
            <NODE_LOCATION x="350" y="146" visible="false"/>
            <NODE_LABEL label="Are Scrollable" shape="1" backColor="A04000" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="Long hints are
s
c
r
o
l
l
a
b
l
e" width="100" height="100" isHTML="false"/>
        </NODE>
        <NODE nodeID="AutoID 1010377910260">
            <NODE_LOCATION x="267" y="342" visible="false"/>
            <NODE_LABEL label="Pictures" shape="2" backColor="FF0000" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="&lt;center&gt;&lt;font size=&quot;4&quot;&gt;&lt;font color=&quot;#FF0000&quot;&gt;Pictures!&lt;/font&gt;  For instance here is one of the TouchGraph Logo&lt;br&gt; &lt;img src=&quot;SmallWingedTriangle.jpg&quot; height=200 width=200&quot;&gt;&lt;/font&gt;&lt;/center&gt;" width="300" height="-1" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1010377955190">
            <NODE_LOCATION x="422" y="413" visible="false"/>
            <NODE_LABEL label="Hyperlinks" shape="1" backColor="A04000" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="&lt;center&gt;&lt;font size=&quot;4&quot;&gt;&lt;font color=&quot;#A04000&quot;&gt;Hyperlinks!&lt;/font&gt;  For instance here is one to &lt;a href=&quot;http://www.touchgraph.com&quot;&gt;TouchGraph.&lt;/a&gt;&lt;/font&gt;&lt;/center&gt;" width="200" height="-1" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1010378016990">
            <NODE_LOCATION x="384" y="58" visible="false"/>
            <NODE_LABEL label="Can be dragged" shape="1" backColor="A04000" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="You can drag a hint around by moving it&apos;s titlebar." width="300" height="-1" isHTML="false"/>
        </NODE>
        <NODE nodeID="AutoID 1010378069490">
            <NODE_LOCATION x="378" y="-62" visible="false"/>
            <NODE_LABEL label="Locality" shape="2" backColor="6060F0" textColor="FFFFFF" fontSize="18"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="&lt;font color =&quot;#6060F0&quot;&gt;&lt;b&gt;Locality Browsing&lt;/b&gt;&lt;/font&gt; is the basis of the LinkBrowser application.  There are two ways to switch locality, by &lt;font color =&quot;#A04000&quot;&gt;&lt;b&gt;browsing&lt;/b&gt;&lt;/font&gt; or &lt;font color =&quot;#A04000&quot;&gt;&lt;b&gt;expanding&lt;/b&gt;&lt;/font&gt;." width="300" height="-1" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1010378170280">
            <NODE_LOCATION x="731" y="-26" visible="true"/>
            <NODE_LABEL label="Nodes" shape="2" backColor="0000E0" textColor="FFFFFF" fontSize="18"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="Nodes can have different Sizes, (determined by the font size), colors, and shapes.  Currently availiable shapes are rectangles, rounded rectangles, and elipses." width="200" height="-1" isHTML="false"/>
        </NODE>
        <NODE nodeID="AutoID 1010378185830">
            <NODE_LOCATION x="848" y="34" visible="false"/>
            <NODE_LABEL label="Shapes" shape="1" backColor="606060" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="" width="300" height="-1" isHTML="false"/>
        </NODE>
        <NODE nodeID="AutoID 1010378195330">
            <NODE_LOCATION x="831" y="-145" visible="false"/>
            <NODE_LABEL label="Sizes" shape="1" backColor="606060" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="" width="300" height="-1" isHTML="false"/>
        </NODE>
        <NODE nodeID="AutoID 1010378522960">
            <NODE_LOCATION x="240" y="-193" visible="false"/>
            <NODE_LABEL label="Browsing" shape="1" backColor="A04000" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="Browsing is done by clicking once on an unselected node.  Doing so will bring up related nodes.  Adjusting the value of the Locality Scrollbar will change the number of nodes that is displayed." width="300" height="-1" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1010378545480">
            <NODE_LOCATION x="213" y="-82" visible="false"/>
            <NODE_LABEL label="Expanding" shape="1" backColor="A04000" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="One can expand or hide nodes by right clicking on a node, and selecting the appropriate option.  &lt;b&gt;Note&lt;/b&gt; Currently, hiding only works if some node is selected." width="300" height="-1" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1010378728110">
            <NODE_LOCATION x="731" y="88" visible="true"/>
            <NODE_LABEL label="Edges" shape="2" backColor="0000E0" textColor="FFFFFF" fontSize="18"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="Edges can have different lenghts and colors.  Currently edges come in two types, directed arrows and undirected bars." width="200" height="-1" isHTML="false"/>
        </NODE>
        <NODE nodeID="AutoID 1010378788190">
            <NODE_LOCATION x="845" y="168" visible="false"/>
            <NODE_LABEL label="Length" shape="1" backColor="606060" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="" width="300" height="-1" isHTML="false"/>
        </NODE>
        <NODE nodeID="AutoID 1010378800720">
            <NODE_LOCATION x="825" y="-33" visible="false"/>
            <NODE_LABEL label="Colors" shape="1" backColor="606060" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="" width="300" height="-1" isHTML="false"/>
        </NODE>
        <NODE nodeID="AutoID 1010380164680">
            <NODE_LOCATION x="87" y="-199" visible="false"/>
            <NODE_LABEL label="Little Red Numbers" shape="1" backColor="FF0000" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="Little red numbers indicate that there is more connections to be seen by clicking on a node, or by expanding it." width="300" height="-1" isHTML="false"/>
        </NODE>
        <NODE nodeID="AutoID 1010381228980">
            <NODE_LOCATION x="632" y="127" visible="true"/>
            <NODE_LABEL label="More!" shape="2" backColor="FF00FF" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="http://www.touchgraph.com/newLB/TGLBInstructions.html" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="Double Click this node, or visit &lt;a href=&quot;http://www.touchgraph.com/newLB/TGLBInstructions.html&quot;&gt;TGLinkBrowser Instructions&lt;/a&gt; for more info." width="200" height="-1" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1010986434600">
            <NODE_LOCATION x="317" y="441" visible="false"/>
            <NODE_LABEL label="Reference external HTML" shape="2" backColor="F00000" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="&lt;frameset rows=&quot;320,*&quot;&gt;
    &lt;frame name=&quot;example&quot; src=&quot;HintFrameExample.html&quot;&gt;
&lt;/frameset&gt;" width="340" height="200" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1011034683130">
            <NODE_LOCATION x="442" y="-162" visible="false"/>
            <NODE_LABEL label="Linking to Other Graphs" shape="1" backColor="F08000" textColor="FFFFFF" fontSize="12"/>
            <NODE_URL url="OtherXML.xml" urlIsLocal="true" urlIsXML="true"/>
            <NODE_HINT hint="One can have nodes &lt;font color =&quot;#F08000&quot;&gt;&lt;b&gt;linking to other graphs&lt;/b&gt;&lt;/font&gt; When such a node is clicked on, a new graph is loaded in the browser.  This is a very useful feature for linking to graphs created by another author. &lt;b&gt;Click this node to see!&lt;/b&gt;" width="300" height="-1" isHTML="true"/>
        </NODE>
        <NODE nodeID="AutoID 1011034911680">
            <NODE_LOCATION x="534" y="-27" visible="true"/>
            <NODE_LABEL label="Navigation" shape="2" backColor="40A000" textColor="FFFFFF" fontSize="18"/>
            <NODE_URL url="" urlIsLocal="false" urlIsXML="false"/>
            <NODE_HINT hint="The old way of &lt;font color =&quot;#40A000&quot;&gt;&lt;b&gt;navigating&lt;/b&gt;&lt;/font&gt; by &lt;font color =&quot;#F08000&quot;&gt;&lt;b&gt;linking to other graphs&lt;/b&gt;&lt;/font&gt; is still is present, and a very powerful new way of navigating via the use of &lt;font color =&quot;#6060F0&quot;&gt;&lt;b&gt;locality&lt;/b&gt;&lt;/font&gt; has been introduced." width="300" height="-1" isHTML="true"/>
        </NODE>
    </NODESET>
    <EDGESET>
        <EDGE fromID="AutoID 1010274200280" toID="AutoID 1010274102450" type="1" length="40" visible="true" color="A0A0A0"/>
        <EDGE fromID="AutoID 1010274564490" toID="AutoID 1010274200280" type="1" length="30" visible="true" color="606060"/>
        <EDGE fromID="AutoID 1010274102450" toID="AutoID 1010377764880" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010274102450" toID="AutoID 1010377835240" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010377764880" toID="AutoID 1010377910260" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010377764880" toID="AutoID 1010377955190" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010274102450" toID="AutoID 1010378016990" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010274200280" toID="AutoID 1010378170280" type="1" length="40" visible="true" color="0000B0"/>
        <EDGE fromID="AutoID 1010378170280" toID="AutoID 1010378185830" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010378170280" toID="AutoID 1010378195330" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010378069490" toID="AutoID 1010378522960" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010378069490" toID="AutoID 1010378545480" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010274200280" toID="AutoID 1010378728110" type="1" length="40" visible="true" color="0000B0"/>
        <EDGE fromID="AutoID 1010378728110" toID="AutoID 1010378788190" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010378728110" toID="AutoID 1010378800720" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010378170280" toID="AutoID 1010378800720" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010378728110" toID="AutoID 1010378185830" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010378545480" toID="AutoID 1010380164680" type="0" length="60" visible="false" color="808080"/>
        <EDGE fromID="AutoID 1010378522960" toID="AutoID 1010380164680" type="0" length="60" visible="false" color="808080"/>
        <EDGE fromID="AutoID 1010274200280" toID="AutoID 1010381228980" type="0" length="30" visible="true" color="808080"/>
        <EDGE fromID="AutoID 1010377764880" toID="AutoID 1010986434600" type="1" length="60" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1010274200280" toID="AutoID 1011034911680" type="1" length="40" visible="true" color="0000B0"/>
        <EDGE fromID="AutoID 1011034911680" toID="AutoID 1010378069490" type="1" length="40" visible="false" color="0000B0"/>
        <EDGE fromID="AutoID 1011034911680" toID="AutoID 1011034683130" type="1" length="40" visible="false" color="0000B0"/>
    </EDGESET>
    <PARAMETERS>
        <PARAM name="offsetX" value="627"/>
        <PARAM name="rotateSB" value="0"/>
        <PARAM name="zoomSB" value="-7"/>
        <PARAM name="offsetY" value="19"/>
    </PARAMETERS>
</TOUCHGRAPH_LB>
